---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  labels:
    app: fortune-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web
  type: NodePort
  selector:
    app: fortune-app
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: fortune-app
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: fortune-app
    template:
      metadata:
        name: fortune-app
        annotations:
          prometheus.io/path: "/actuator/prometheus"
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
        labels:
          app: fortune-app
      spec:
    spec:
      containers:
      - image: ryandotclair/fortune:1.0
        name: fortune-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_REDIS_HOST
          value: "redis.default.svc.cluster.local"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
