---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: fortune-prod
spec:
  replicas: 1
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - image: harbor.corp.local/library/redis:1.0
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
